### ISSUE TITLE
plot 

### ISSUE THREAD

**Issue by DiyaVaka** [spundhir/idr#1]
Hi,

Thank you for making this public. I was able to use this for our data. What I have issue with is I am trying to make sense of the plots from the batch consistency plot script. What does slope here mean?

Thanks,

Diya

**Comment by spundhir** [comment]
Hi Diya,

I presume you meant a plot similar to Figure6c from this paper (https://genome.cshlp.org/content/22/9/1813.full). It essentially means how irreproducibility the called peaks are between replicates. As you see in the figure, top 30,000 peaks are highly reproducible (low IDR), after which the IDR steeply increases (as evident from the slope) and it means that many of these peaks are false positives.
